/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PaymentSplitter__factory } from "./PaymentSplitter__factory";
export { PaymentSplitter3__factory } from "./PaymentSplitter3__factory";
