/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PaymentSplitter } from "./PaymentSplitter";
export type { PaymentSplitter3 } from "./PaymentSplitter3";
